### ISSUE TITLE
 无法获取login token

### ISSUE THREAD

**Issue by mark-yjx** [feizao67/GDUF_autocheck#1]
# 求助

在**iOS**上使用**stream**抓包按照步骤到返回易班打开易广金时会显示 ：
> 网页加载失败，错误信息：
An SSL error has occurred and a secure connection to the server cannot be made.
>
而在电脑使用**wireshark**开手机热点抓包也没有http的包。

**Comment by feizao67** [comment]
stream抓包你看看是不是没有配置https抓包，如图
![Uploading E007B232-5742-449F-82D5-68C258AAEBB0.png…]()

**Comment by feizao67** [comment]
stream抓包你看看是不是没有配置https抓包，如图
![F06B451E-2B41-4B37-95F9-F41AE32BA333](https://user-images.githubusercontent.com/37013075/156866536-ec59fe0f-95f8-4d12-9a54-4439656db48d.png)

**Comment by mark-yjx** [comment]
> stream抓包你看看是不是没有配置https抓包，如图 ![F06B451E-2B41-4B37-95F9-F41AE32BA333](https://user-images.githubusercontent.com/37013075/156866536-ec59fe0f-95f8-4d12-9a54-4439656db48d.png)

好的，已解决，谢谢
